# Generated by Django 3.1 on 2020-09-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteTitle', models.CharField(max_length=30)),
                ('sitePhone', models.IntegerField()),
                ('siteLogo', models.ImageField(blank=True, upload_to='siteImages/')),
                ('siteEmail', models.EmailField(max_length=254)),
                ('siteAddress', models.CharField(max_length=250)),
                ('siteAbout', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='siteImages/slider')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
