# Generated by Django 3.1 on 2020-09-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='siteAbout',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='siteLogo',
            field=models.ImageField(blank=True, upload_to='siteImages/'),
        ),
    ]
