# Generated by Django 3.1 on 2020-09-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSettings', '0002_setting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contact_page_banner',
            field=models.ImageField(blank=True, upload_to='siteImages/contact_page_banner'),
        ),
        migrations.AddField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
