# Generated by Django 3.1 on 2020-09-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSettings', '0002_auto_20200913_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(blank=True, upload_to='siteImages/slider')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
