# Generated by Django 3.1 on 2020-09-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteSettings', '0003_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='image_one',
            new_name='image',
        ),
    ]
