# Generated by Django 3.1 on 2020-09-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('order', '0003_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='product',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='product',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
