# Generated by Django 3.1 on 2020-09-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='New', max_length=30),
        ),
    ]
